<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="base_length" value="0.4"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="base_mass" value="5"/>

    <xacro:property name="wheel_radius" value="${base_height/2}"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="wheel_mass" value="1"/>

    <xacro:property name="camera_length" value="0.01"/>
    <xacro:property name="camera_width" value="0.08"/>
    <xacro:property name="camera_height" value="0.06"/>
    <xacro:property name="camera_mass" value="0.04"/>

    <xacro:property name="camera_sphere_mass" value="0.04"/>
    <xacro:property name="camera_sphere_radius" value="${camera_height/2.0}"/>
    








    <xacro:macro name="cuboid_link" params="prefix m l b h x y z r p yaw " >
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <box size="${l} ${b} ${h}"/>
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="${r} ${p} ${yaw}"/>
                <material name="green"/>
            </visual>
            <xacro:cuboid_collision lbh="${l} ${b} ${h}" o_xyz="${x} ${y} ${z}" o_rpy="${r} ${p} ${yaw}"/>
            <xacro:cuboid_inertia m="${m}" x="${x}" y="${y}" z="${z}" o_xyz="${x} ${y} ${z}" o_rpy="${r} ${p} ${yaw}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="cube_link" params="prefix m l b h x y z r p yaw " >
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <box size="${l} ${b} ${h}"/>
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="${r} ${p} ${yaw}"/>
                <material name="red"/>
            </visual>
            <xacro:cuboid_collision lbh="${l} ${b} ${h}" o_xyz="${x} ${y} ${z}" o_rpy="${r} ${p} ${yaw}"/>
            <xacro:cuboid_inertia m="${m}" x="${x}" y="${y}" z="${z}" o_xyz="${x} ${y} ${z}" o_rpy="${r} ${p} ${yaw}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="small_cuboid_link" params="prefix m l b h x y z r p yaw " >
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <box size="${l} ${b} ${h}"/>
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="${r} ${p} ${yaw}"/>
                <material name="grey"/>
            </visual>
            <xacro:cuboid_collision lbh="${l} ${b} ${h}" o_xyz="${x} ${y} ${z}" o_rpy="${r} ${p} ${yaw}"/>
            <xacro:cuboid_inertia m="${m}" x="${x}" y="${y}" z="${z}" o_xyz="${x} ${y} ${z}" o_rpy="${r} ${p} ${yaw}"/>
        </link>
    </xacro:macro>


    <xacro:macro name="wheel_link" params="prefix m r l x y z roll p yaw">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${r}" length="${l}"/>
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="${roll} ${p} ${yaw}"/>
                <material name="blue"/>
            </visual>
            <xacro:cylinder_inertia m="${m}" r="${r}" l="${l}" o_xyz="${x} ${y} ${z}" o_rpy="${roll} ${p} ${yaw}"/>
            <xacro:cylinder_collision r="${r}" l="${l}" o_xyz="${x} ${y} ${z}" o_rpy="${roll} ${p} ${yaw}"/>
        </link>
    </xacro:macro>


    <xacro:macro name="sphere_link" params="prefix m r x y z roll p yaw">
        <link name="${prefix}_sphere_link">
            <visual>
                <geometry>
                    <sphere radius="${r}"/>
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="${roll} ${p} ${yaw}"/>
                <material name="yellow"/>
            </visual>
            <xacro:sphere_inertia m="${m}" r="${r}" o_xyz="${x} ${y} ${z}" o_rpy="${roll} ${p} ${yaw}"/>
            <xacro:sphere_collision r="${r}" o_xyz="${x} ${y} ${z}" o_rpy="${roll} ${p} ${yaw}"/>
        </link>
    </xacro:macro>


    <link name="odom"/>
    <joint name="odom_to_base_footprint" type="fixed">
        <parent link="odom"/>
        <child  link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <link name="base_footprint"/>

    <xacro:cuboid_link prefix="base" m="${base_mass}" l="${base_length}" b="${base_width}" h="${base_height}" x="0" y="0" z="${base_height/2}" r="0" p="0" yaw="0"/>

    <xacro:wheel_link prefix="rear_right" m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}" x="0" y="0" z="0" roll="${pi/2}" p="0" yaw="0"/>

    <xacro:wheel_link prefix="rear_left" m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}" x="0" y="0" z="0" roll="${pi/2}" p="0" yaw="0"/>

    <xacro:wheel_link prefix="front_right" m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}" x="0" y="0" z="0" roll="${pi/2}" p="0" yaw="0"/>

    <xacro:wheel_link prefix="front_left" m="${wheel_mass}" l="${wheel_length}" r="${wheel_radius}" x="0" y="0" z="0" roll="${pi/2}" p="0" yaw="0"/>

    <xacro:small_cuboid_link prefix="camera" m="${camera_mass}" l="${camera_length}" b="${camera_width}" h="${camera_height}" x="0" y="0" z="0" r="0" p="0" yaw="0"/>


    <xacro:sphere_link prefix="camera" m="${camera_sphere_mass}"  r="${camera_sphere_radius}" x="0" y="0" z="0" roll="0" p="0" yaw="0"/>

    <link name="optical_camera_link">
        <visual>
            <geometry>
                <cylinder radius="0.02" length="0.01"/>
            </geometry>
            <origin xyz="0 0 -0.005" rpy="0 ${pi/2.0} 0"/>
            <material name="black"/>
        </visual>
        <xacro:cylinder_inertia m="0.02" r="0.03" l="0.01" o_xyz="0 0 -0.005" o_rpy="0 ${pi/2.0} 0"/>
        <xacro:cylinder_collision r="0.03" l="0.01" o_xyz="0 0 -0.005" o_rpy="0 ${pi/2.0} 0"/>
    </link>






    <joint name="base_footprint_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </joint>


    <joint name="base_rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <axis xyz="0 1 0"/>        
        <origin xyz="${-base_length/3} ${-((base_width/2)+(wheel_length/2))} 0" rpy="0 0 0"/>
        <limit effort="100" velocity="10"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>


    <joint name="base_rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <axis xyz="0 1 0"/>        
        <origin xyz="${-base_length/3} ${((base_width/2)+(wheel_length/2))} 0" rpy="0 0 0"/>
        <limit effort="100" velocity="10"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <axis xyz="0 1 0"/>        
        <origin xyz="${base_length/3} ${-((base_width/2)+(wheel_length/2))} 0" rpy="0 0 0"/>
        <limit effort="100" velocity="10"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <axis xyz="0 1 0"/>        
        <origin xyz="${base_length/3} ${((base_width/2)+(wheel_length/2))} 0" rpy="0 0 0"/>
        <limit effort="100" velocity="10"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <!-- <joint name="base_camera_sphere_joint" type="revolute">
        <parent link="base_link"/>
        <child link="camera_sphere_link"/>
        <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-pi/2.0}" upper="${pi/2.0}" effort="100" velocity="100"/>
        <dynamics friction="0.3" damping="0.1"/>
    </joint> -->

    <joint name="base_camera_sphere_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_sphere_link"/>
        <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
    </joint>


    <joint name="sphere_camera_link" type="fixed">
        <parent link="camera_sphere_link"/>
        <child link="camera_link"/>
        <origin xyz="${camera_sphere_radius+(camera_length/2.0)} 0 0" rpy="0 0 0"/>
    </joint>


    <joint name="camera_optical_camera_link" type="fixed">
        <parent link="camera_link"/>
        <child link="optical_camera_link"/>
        <origin xyz="${camera_length*1.5} 0 0" rpy="0 0 0"/>
    </joint>

    

    <xacro:cube_link prefix="scan" m="1.2" l="0.1" b="0.1" h="0.1" x="0" y="0" z="0.05" r="0" p="0" yaw="0"/>


    <joint  name="scan_joint" type="fixed">
        <origin xyz="0.0 0 0.2" rpy="0 0 0"/>
        <child link="scan_link"/>
        <parent link="base_link"/>
    </joint>

    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="imu_link" />
    </joint>




    <xacro:small_cuboid_link prefix="c_up" m="0.02" l="0.03" b="0.08" h="0.01" x="0.015" y="0" z="0" r="0" p="0" yaw="0"/>

    <xacro:small_cuboid_link prefix="c_down" m="0.02" l="0.03" b="0.08" h="0.01" x="0.015" y="0" z="0" r="0" p="0" yaw="0"/>

    <xacro:small_cuboid_link prefix="c_right" m="0.02" l="0.03" b="0.01" h="0.06" x="0.015" y="0" z="0" r="0" p="0" yaw="0"/>

    <xacro:small_cuboid_link prefix="c_left" m="0.02" l="0.03" b="0.01" h="0.06" x="0.015" y="0" z="0" r="0" p="0" yaw="0"/>

    <joint name="base_c_up_joint" type="fixed">
        <parent link="base_link"/>
        <child link="c_up_link"/>
        <origin xyz="${base_length/2.0} 0 0.13" rpy="0 0 0"/>
    </joint>

    <joint name="base_c_down_joint" type="fixed">
        <parent link="base_link"/>
        <child link="c_down_link"/>
        <origin xyz="${base_length/2.0} 0 0.07" rpy="0 0 0"/>
    </joint>

    <joint name="base_c_right_joint" type="fixed">
        <parent link="base_link"/>
        <child link="c_right_link"/>
        <origin xyz="${base_length/2.0} -0.04 0.1" rpy="0 0 0"/>
    </joint>

    <joint name="base_c_left_joint" type="fixed">
        <parent link="base_link"/>
        <child link="c_left_link"/>
        <origin xyz="${base_length/2.0} 0.04 0.1" rpy="0 0 0"/>
    </joint>
</robot>
